// This is a placeholder for a dynamic blog article page.
// You would fetch article content based on the articleSlug here.
import Image from "next/image";
import { ArticleContent } from "@/components/blog/ArticleContent";

interface ArticlePageProps {
  params: {
    articleSlug: string;
  };
}

export default function ArticlePage({ params }: ArticlePageProps) {
  const { articleSlug } = params;

  // Mock article data - replace with actual data fetched from MongoDB
  // The heroImage here would eventually be a Cloudinary URL from your database
  const mockArticle = {
    title: "Sustainable Periods: Why Menstrual Cups Are a Game-Changer",
    heroImage: "https://res.cloudinary.com/dsvexizbx/image/upload/v1754083815/Banner_Content_iofvod.png", // Placeholder Cloudinary URL
    content: `
      <p>In an era increasingly defined by environmental consciousness, the choices we make daily, even those seemingly personal, are under scrutiny for their ecological footprint. Menstrual hygiene products, a necessity for billions worldwide, is no exception. While often overlooked, yet with significant environmental implications, is menstrual hygiene. For decades, disposable pads and tampons have been the norm, but a growing awareness of their ecological footprint is paving the way for more sustainable alternatives with the menstrual cup leading the charge.</p>

      <p>The sheer volume of waste generated by traditional menstrual products is staggering. Globally, billions of pads and tampons are discarded annually, contributing to overflowing landfills and polluting our oceans. Composed primarily of plastics and synthetic materials, they can take hundreds of years to decompose. Furthermore, the manufacturing processes for these items require substantial resources, including water and energy, and often involve the use of pesticides and chemicals, further harming ecosystems.</p>

      <p>Enter the menstrual cup: a reusable, bell-shaped device typically made from medical-grade silicone. Designed to be inserted into the vagina to collect menstrual fluid, it offers a sustainable and often more comfortable alternative to its disposable counterparts.</p>

      <h3>Here's why menstrual cups are a game-changer:</h3>
      <ul>
        <li><strong>Waste Reduction:</strong> This is arguably the most significant environmental benefit. A single menstrual cup, with proper care, can last for up to 10 years. Imagine the reduction in landfill waste when one cup replaces thousands of disposable pads or tampons over a decade.</li>
        <li><strong>Reduced Carbon Footprint:</strong> The production of menstrual cups requires significantly less energy compared to the continuous production of disposable products. This translates to less water, energy, and raw materials being used over time.</li>
        <li><strong>Chemical-Free:</strong> Many disposable products contain fragrances, dyes, and other chemicals that can be harmful to both the user and the environment. Menstrual cups, typically made from inert medical-grade silicone, offer a more natural and chemical-free option.</li>
      </ul>

      <h3>Beyond Environmental Benefits: Personal Advantages</h3>
      <p>Beyond their impressive environmental credentials, menstrual cups, their personal benefits are equally compelling:</p>
      <ul>
        <li><strong>Cost-Effective:</strong> While the initial investment might be higher than a single pack of disposables, the long-term savings are substantial. Over a decade, a user can save hundreds, if not thousands, of dollars.</li>
        <li><strong>Comfort and Convenience:</strong> Many users report greater comfort and less leakage with menstrual cups compared to pads or tampons. They can be worn for longer periods (up to 12 hours), offering more freedom and less interruption to daily activities, including swimming and exercise.</li>
        <li><strong>Reduced Health Risks:</strong> Unlike tampons, menstrual cups are not associated with Toxic Shock Syndrome (TSS) as they collect rather than absorb menstrual fluid.</li>
        <li><strong>Better Understanding of Your Body:</strong> Using a menstrual cup can provide a more direct and often less messy way to understand your flow.</li>
      </ul>

      <h3>Addressing Challenges and Promoting Adoption</h3>
      <p>Switching to a menstrual cup can feel daunting for some, but with a bit of practice, it becomes second nature. Initial challenges might include finding the right size and insertion technique. To overcome these, education and support are crucial. However, the abundance of online resources, instructional videos, and supportive communities makes the transition smoother than ever before.</p>

      <h3>Conclusion</h3>
      <p>The menstrual cup represents a significant stride towards more sustainable living, particularly within the realm of personal care. By drastically reducing waste, minimizing resource consumption, and offering a healthier, more comfortable alternative, it empowers individuals to make a tangible positive impact on the environment, one period at a time. For collectively strive for a greener future, embracing innovations like the menstrual cup is not just a personal choice, but a powerful step towards a more sustainable planet for all.</p>
    `,
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <p className="text-sm text-gray-500 mb-4">Home / Product / Blog / Blog Article</p>
      <ArticleContent article={mockArticle} />
    </div>
  );
}
