// src/components/admin/finances/DocumentsTab.tsx
import React from 'react';

// We updated this interface to perfectly match the parent component
interface IReportLog {
  _id: string; 
  reportId: string; 
  title: string; 
  periodLabel: string;
  preparedBy: string; 
  generatedByEmail: string; 
  totalIncome: number;
  totalExpense: number; 
  netBalance: number; 
  createdAt: string;
  preparedBySignature?: string; 
  authorizedSignatorySignature?: string;
}

interface DocumentsTabProps {
  reportLogs: IReportLog[];
  handleDownloadHistorical: (log: IReportLog) => void;
  onOpenEmailModal: (log: IReportLog) => void;
}

export function DocumentsTab({ reportLogs, handleDownloadHistorical, onOpenEmailModal }: DocumentsTabProps) {
  return (
    <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-100 dark:border-gray-800 bg-gray-50/50">
        <h3 className="font-bold text-gray-900 dark:text-white">Generated PDF Reports Archive</h3>
      </div>
      <div className="divide-y divide-gray-100 dark:divide-gray-800 overflow-x-auto w-full">
        <table className="w-full text-left whitespace-nowrap">
          <thead className="bg-gray-50 dark:bg-gray-800/50 text-xs text-gray-500 uppercase">
            <tr><th className="p-4">Report ID</th><th className="p-4">Title</th><th className="p-4">Generated By</th><th className="p-4">Date</th><th className="p-4 text-right">Actions</th></tr>
          </thead>
          <tbody className="text-sm divide-y divide-gray-100 dark:divide-gray-800">
            {reportLogs.map(log => (
              <tr key={log._id} className="hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors">
                <td className="p-4 font-mono font-bold text-gray-900 dark:text-white">{log.reportId}</td>
                <td className="p-4 text-gray-900 dark:text-white">{log.title}</td>
                <td className="p-4 text-gray-500 dark:text-gray-400">{log.generatedByEmail || log.preparedBy || 'Admin'}</td>
                <td className="p-4 text-gray-500 dark:text-gray-400">{new Date(log.createdAt).toLocaleDateString()}</td>
                <td className="p-4 text-right flex justify-end gap-2">
                  <button onClick={() => handleDownloadHistorical(log)} className="px-3 py-1.5 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 rounded-lg font-semibold hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors">
                    Download
                  </button>
                  <button onClick={() => onOpenEmailModal(log)} className="px-3 py-1.5 bg-purple-50 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 rounded-lg font-semibold hover:bg-purple-100 dark:hover:bg-purple-900/50 transition-colors">
                    Email
                  </button>
                </td>
              </tr>
            ))}
            {reportLogs.length === 0 && <tr><td colSpan={5} className="p-8 text-center text-gray-500 dark:text-gray-400">No reports generated yet.</td></tr>}
          </tbody>
        </table>
      </div>
    </div>
  );
}